services:
  bot:
    build:
      context: .
    volumes:
      - ./what_to_wear_outside_bot:/what_to_wear_outside_bot
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: >
      sh -c "python bot.py"
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres